#lists.py
replacement = [
    ("á", "a"), ("ä", "a"), ("ă", "a"),
    ("č", "c"), ("ď", "d"),
    ("é", "e"), ("ě", "e"),
    ("í", "i"),
    ("ň", "n"),
    ("ó", "o"), ("ö", "o"),
    ("ř", "r"),
    ("š", "s"),
    ("ť", "t"),
    ("ú", "u"), ("ů", "u"), ("ü", "u"),
    ("ý", "y"),
    ("ž", "z"),

    ("Á", "A"), ("Ä", "A"), ("Ă", "A"),
    ("Č", "C"), ("Ď", "D"),
    ("É", "E"), ("Ě", "E"),
    ("Í", "I"),
    ("Ň", "N"),
    ("Ó", "O"), ("Ö", "O"),
    ("Ř", "R"),
    ("Š", "S"),
    ("Ť", "T"),
    ("Ú", "U"), ("Ů", "U"), ("Ü", "U"),
    ("Ý", "Y"),
    ("Ž", "Z"),

    (",", "_"),
    (")", "_"),
    ("(", "_"),
    ("#", "_"),
    ("+", "_"),
    ("´", "_"),
    (".", "_"),
    ("“", "_"),
    ("„", "_"),
    ("–", "-"),
    ("-", "_"),
    ("§", "_"),
    ("=", "_"),
    ("[", "_"),
    ("]", "_"),
    ("$", "_"),
    ("~", "_"),
    ("!", "_"),
    (";", "_"),
    (":", "_")
]

do_not_rename = [
    "CORE-02_Technicka_zprava",
    "CORE-03_Revizni_zpravy",
    "CORE-04_Navody_manualy",
    "CORE-05_Certifikaty",
    "CORE-06_Merici_protokoly",
    "CORE-07_Ostatni",
    "CW-01_Staticky_vypocet",
    "CW-02_Hygiena",
    "CW-03_Pozarni_ochrana",
    "CW-04_Stavebni_povoleni",
    "CW-05_Projekt_elektro",
    "CW-06_Katastralni_mapa_LV",
    "CW-07_Pristupova_cesta_SAD",
    "CW-09_Kolaudace",
    "CW-10_Hygienicke_mereni",
    "CW-11_Antenni_plan&kab_trasy_MAX",
    "CW-12_Revizni_zprava_elektro&hromo",
    "CW-18_Realizacni_dokumentace",
    "CW-19_Technicka_zprava",
    "CW-20_Plan_uniku_a_umisteni_PHP",
    "CW-22_Predavaci_protokoly",
    "CW-23_Dalsi_povoleni",
    "CW-24_Zarucni_listy_a_certifikaty",
    "CW-25_Provozni_denik&HS",
    "CW-26_Smlouvy_elektro",
    "CW-29_Najemni_smlouvy",
    "CW-30_Alarm",
    "CW-31_Klimatizace",
    "FO-01_Studie",
    "FO-02_Katastralni_mapa_LV",
    "FO-03_BPD",
    "FO-04_Stavebni_povoleni",
    "FO-05_Kolaudace",
    "FO-06_Dalsi_povoleni",
    "FO-07_Predavaci_protokoly",
    "FO-08_Smlouvy",
    "FO-09_Geodeticke_zamereni",
    "FO-10_Schema",
    "FO-11_Mereni,protokoly",
    "FO-12_DSPS_linie",
    "FO-13_TZ&BoM_linie",
    "FO-14_DSPS_FTTH",
    "FO-15_TZ&BoM_FTTH",
    "FO-16_Stavebni_denik",
    "FO-17_Zarucni_listy_a_certifikaty",
    "TW-01_Sklad",
    "TW-02_Commissioning",
    "TW-03_PSU",
    "TW-05_Antenni_plan_AsBuilt",
    "TW-06_Mereni_RF_anten",
    "TW-08_MW_cast",
    "TW-09_Optika",
    "VT-01_Technicky_souhlas"
]